/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Date;

import redis.clients.jedis.Jedis;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Jedis jedis = new Jedis();
        int index = 0;
        while (true) {
            String message = "{\"timestamp\":" + (new Date()).getTime() + ",\"index\":" + index + "}";
            jedis.rpush("channel", message);
            System.out.println(message);
            index++;
            Thread.sleep(1000);
        }
    }
}
