/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Date;

import com.google.gson.Gson;

import redis.clients.jedis.Jedis;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Jedis jedis = new Jedis();
        Gson gson = new Gson();
        int index = 0;
        while (true) {
            TestMessage message = new TestMessage(index, (new Date()).getTime(), 0);
            String json = gson.toJson(message);
            jedis.rpush("channel", json);
            System.out.println(json);
            index++;
            Thread.sleep(1000);
        }
    }
}
