/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.Instant;
import java.util.Random;

import com.google.gson.Gson;

import redis.clients.jedis.Jedis;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Jedis jedis = new Jedis();
        Gson gson = new Gson();
        Random random = new Random();
        int index = 0;
        while (true) {
            TestMessage message = new TestMessage(
                    index,
                    Instant.now().toEpochMilli(),
                    random.nextInt(1, 4));
            String json = gson.toJson(message);
            jedis.rpush("test-message", json);
            System.out.println(json);
            index++;
            Thread.sleep(200);
        }
    }
}
